# User Settings | Edit there as per required

title: Fady Sadek
url: "http://fadysadek.me/"
baseurl: "/"

# This will show up at the top of index page
site_heading: >
    Fady <span class="faded">'s blog</span>

email: fadysamirsadek@live.com
author: Fady Sadek
# This description will show up in google search results
# (for index page) etc.
description: >
    This Blog is about javascript and some other stuff 

# This will what will show against &copy; in the footer
copyright: Fady Sadek
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    I am a geek who is currently in his second year of his computer science degree<br/>
    I like coding , blog , music , soda. This blog will be my way to share my thoughts and weird intrests with the world.

permalink: /:title.html

# Comments are powered by disqus
comments: true

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    I do javascript and some other stuff.

about_footer: true

twitter_username: fadysamirsadek
github_username: fadysamirsadek
facebook_id: fadysamirsadek

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/profile-picture.jpg
paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-69243698-7 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/accent.png" # This will show in facebook thumbnails
twitter_image: "http://ankitsultana.com/images/accent.png?1234" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

gems:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
